#include "backend.h"
#include <stdio.h>

void backend_with_string(void *ctx, void(*o_cb)(void *ctx, const char *result)) {
    printf("- In function foo() inside C code\n");
    printf("- Calling function passed to us by Java...\n");

    const char *my_name = "This string has been generated by C backend code";
    o_cb(ctx, my_name);

    printf("- Finished invoking the given callback. Now back in C code."
            " Returning back to Java...\n");
}
