#include "backend.h"

#include <malloc.h>
#include <pthread.h>
#include <stdio.h>

void backend_with_string(void *ctx, void(*o_cb)(void *ctx, const char *result)) {
    printf("- In function backend_with_string() inside C code\n");
    printf("- Calling the function passed to us by Java...\n");

    const char *result = "This string has been generated by C backend code";
    o_cb(ctx, result);

    printf("- Finished invoking the given callback. Now back in C code."
            " Returning back to Java...\n");
}



typedef struct backend_with_string_async_thread_args {
    pthread_t thread_id;
    void *ctx;
    void(*o_cb)(void *ctx, const char *result);
} backend_with_string_async_thread_args;

static void* backend_with_string_async_routine(void *arg) {
    printf("- In a new thread backend_with_string_async_routine() inside C code\n");

    backend_with_string_async_thread_args *args = (backend_with_string_async_thread_args*)arg;

    printf("- Calling the function passed to us by Java...\n");

    const char *result = "This string has been generated by async C backend code";
    args->o_cb(args->ctx, result);

    printf("- Finished invoking the given callback. Now back in C code."
            " Exiting thread...\n");

    free(args);

    return 0;
}

void backend_with_string_async(void *ctx, void(*o_cb)(void *ctx, const char *result)) {
    printf("- In function backend_with_string_async() inside C code\n");

    backend_with_string_async_thread_args *args = (backend_with_string_async_thread_args*)malloc(
            sizeof(backend_with_string_async_thread_args));
    args->ctx = ctx;
    args->o_cb = o_cb;

    if (pthread_create(&args->thread_id, 0, backend_with_string_async_routine, args)) {
        printf("- ERROR: Could not create a thread !!\n");
        // o_cb(ctx, 0);
    }
}
