#!/bin/bash

set -e;

backend_src_dir="./../backend-src";
csharp_build_dir="./build/csharp";
native_build_dir="./build/native";

if [ ! -d "${csharp_build_dir}" ]; then
    mkdir -p ${csharp_build_dir};
fi

if [ ! -d "${native_build_dir}" ]; then
    mkdir -p ${native_build_dir}
fi

# swig -csharp -c++ -dllimport "frontend" -I"${backend_src_dir}" -o "${native_build_dir}"/csharp_wrap.cxx -outdir "${csharp_build_dir}" swig_ifc.i

g++ -std=c++14 -shared -O2 -s -fPIC "${backend_src_dir}"/backend.cxx -I"${backend_src_dir}" -o "${native_build_dir}"/libbackend.so;
# g++ -std=c++14 -shared -O2 -s -fPIC "${native_build_dir}"/csharp_wrap.cxx -I. -I"${csharp_build_dir}" -I"${backend_src_dir}" -L"${native_build_dir}" -lbackend -o "${native_build_dir}"/libfrontend.so;

mcs -lib:"#{csharp_build_dir}" Frontend.cs NativeBindings.cs

LD_LIBRARY_PATH="${native_build_dir}" ./Frontend.exe
